---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# url-download-action
name: "🌍 Download Content from URL"
description: "Uses WGET to download the content at a given URL"

inputs:
  # Mandatory
  URL:
    description: "URL to download"
    required: true
  # Optional
  EXIT_ON_FAIL:
    description: "Exit with error if download fails"
    required: false
    default: true
  NO_CLOBBER:
    description: "Will not overwrite existing local file"
    required: false
    default: false
  PATH:
    description: "Saves file to given path"
    required: false

runs:
  using: "composite"
  steps:
    - name: "Verify WGET is available"
      shell: bash
      run: |
        # Verify WGET is available
        WGET_CMD=$(which wget)
        if [ ! -x $WGET_CMD ]; then
          echo "Unable to find/install WGET command ❌"
          echo "Check instance type and OS environment"
          exit 1
        fi

    - name: "Download content at URL"
      shell: bash
      # yamllint disable rule:line-length
      run: |
        # Download content at URL

        # Process inputs, set variable/parameters
        URL="${{ inputs.url }}"
        if [[ "f${{ inputs.no_clobber }}" = "ftrue" ]]; then
          WGET_FLAGS="--no-clobber"
        fi
        if [[ "f${{ inputs.no_clobber }}" = "ftrue" ]]; then
          WGET_FLAGS="$WGET_FLAGS -O ${{ inputs.path }}"
        fi

        echo "Downloading content from:"
        echo "$URL"

        # Perform the download
        wget ${{ inputs.url }} $WGET_FLAGS --spider -q || true

        # Validate download, exit appropriately
        DOWNLOAD=$(basename ${{ inputs.url }})
        if [ -f "$DOWNLOAD" ]; then
          echo "Content successfully downloaded ✅"
        else
          echo "Error: content download failed ❌"
          if [[ "f${{ inputs.exit_on_fail }}" = "ftrue" ]]; then
            # Dependent on the action's inputs
            exit 1
          fi
        fi
