---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation

# openssf-scorecard-summary-action
name: "ðŸ“„ OpenSSF Scorecard Summary Output"
description: "Provides summary output with URL (upstream action neglects this)"

runs:
  using: "composite"
  steps:
    - name: "Repository metadata"
      id: repository-metadata
      # yamllint disable-line rule:line-length
      uses: lfit/releng-reusable-workflows/.github/actions/repository-metadata-action@11530dee75e77f063c6e01ac7f3a6cb0cdc95db7 # 2025-02-05

    - name: "Print summary/job output"
      shell: bash
      # yamllint disable rule:line-length
      run: |
        # Print summary/job output
        # ToDo: Update the link below
        echo "## ðŸ” OpenSSF Scorecard Results" >> "$GITHUB_STEP_SUMMARY"
        echo "ðŸ”— https://scorecard.dev/viewer/?uri=github.com/${{ steps.repository-metadata.outputs.repository_owner }}/${{ steps.repository-metadata.outputs.repository_name }}" >> "$GITHUB_STEP_SUMMARY"
