---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2023 The Linux Foundation

name: Compose Maven Verify

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      GERRIT_BRANCH:
        description: "Branch that change is against"
        required: true
        type: string
      GERRIT_CHANGE_ID:
        description: "The ID for the change"
        required: true
        type: string
      GERRIT_CHANGE_NUMBER:
        description: "The Gerrit number"
        required: false
        type: string
      GERRIT_CHANGE_URL:
        description: "URL to the change"
        required: false
        type: string
      GERRIT_EVENT_TYPE:
        description: "Type of Gerrit event"
        required: false
        type: string
      GERRIT_PATCHSET_NUMBER:
        description: "The patch number for the change"
        required: false
        type: string
      GERRIT_PATCHSET_REVISION:
        description: "The revision sha"
        required: false
        type: string
      GERRIT_PROJECT:
        description: "Project in Gerrit"
        required: false
        type: string
      GERRIT_REFSPEC:
        description: "Gerrit refspec of change"
        required: false
        type: string
      JDK_VERSION:
        description: "OpenJDK version"
        required: false
        default: "17"
        type: string
      MVN_VERSION:
        description: "Maven version"
        required: false
        default: "3.8.2"
        type: string
      MVN_PARAMS:
        description: "Maven parameters to pass to the mvn command"
        required: false
        default: ""
        type: string
      MVN_PHASES:
        description: "Comma separated list of phases to execute"
        required: false
        default: "clean deploy"
        type: string
      MVN_OPTS:
        description: "Maven options"
        required: false
        # yamllint disable rule:line-length
        default: >-
          -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
          -Dmaven.repo.local=/tmp/r -Dorg.ops4j.pax.url.mvn.localRepository=/tmp/r
          -DaltDeploymentRepository=staging::default::file:"${GITHUB_WORKSPACE}"/m2repo
        # yamllint enable rule:line-length
        type: string
      MVN_POM_FILE:
        description: "Path to pom.xml file."
        required: false
        default: "pom.xml"
        type: string
      MVN_PROFILES:
        description: "Comma-delimited list of profiles to activate"
        required: false
        default: ""
        type: string
      MVN_GLOBAL_SETTINGS:
        description: "Maven global settings configuration."
        required: false
        default: ${{ vars.GLOBAL_SETTINGS }}
        type: string
      ENV_VARS:
        # yamllint disable-line rule:line-length
        description: "Pass GitHub variables to be exported as environment variables via `toJSON(vars)` or specific variables encoded in JSON format"
        required: false
        default: "{}"
        type: string
      ENV_SECRETS:
        # yamllint disable-line rule:line-length
        description: "Pass GitHub secrets to be exported as environment variables via `toJSON(secrets)` or specific secrets encoded in JSON format"
        required: false
        default: "{}"
        type: string
      POST_BUILD_SCRIPT:
        description: "Post-build script to run after Maven build"
        required: false
        default: ""
        type: string
      POST_BUILD_SCRIPT_PATH:
        description: "Path to post-build script to run after Maven build"
        required: false
        default: ""
        type: string
      POST_BUILD_SCRIPT_URL:
        description: "URL of post-build script to run after Maven build"
        required: false
        default: ""
        type: string
      PRE_BUILD_SCRIPT:
        description: "Pre-build script to run before Maven build"
        required: false
        default: ""
        type: string
      PRE_BUILD_SCRIPT_PATH:
        description: "Path to pre-build script to run before Maven build"
        required: false
        default: ""
        type: string
      PRE_BUILD_SCRIPT_URL:
        description: "URL of pre-build script to run before Maven build"
        required: false
        default: ""
        type: string

concurrency:
  # yamllint disable-line rule:line-length
  group: compose-maven-verify-${{ github.workflow }}-${{ github.event.inputs.GERRIT_BRANCH}}-${{ github.event.inputs.GERRIT_CHANGE_ID || github.run_id }}
  cancel-in-progress: true

jobs:
  maven-verify:
    runs-on: ubuntu-latest
    env:
      PRE_BUILD: ""
      POST_BUILD: ""
    steps:
      # yamllint disable-line rule:line-length
      - uses: lfreleng-actions/checkout-gerrit-change-action@f87b90a3370e62dad310797fedc7fd3700c75832  # v1.0.2
        with:
          gerrit-refspec: ${{ inputs.GERRIT_REFSPEC }}
          gerrit-project: ${{ inputs.GERRIT_PROJECT }}
          gerrit-url: ${{ vars.GERRIT_URL }}
          delay: "0s"
      # yamllint disable-line rule:line-length
      - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        id: setup-python
        with:
          python-version: "3.8"
      - name: Pre-build path
        if: ${{ inputs.PRE_BUILD_SCRIPT_PATH != '' }}
        # yamllint disable rule:line-length
        run: |
          echo "PRE_BUILD=${{ inputs.PRE_BUILD_SCRIPT_PATH }}" >> "$GITHUB_ENV"
        # yamllint enable rule:line-length
      - name: Pre-build script
        if: ${{ inputs.PRE_BUILD_SCRIPT != '' }}
        run: |
          cat > "${{ github.run_id }}-pre.sh" << 'EOF'
          ${{ inputs.PRE_BUILD_SCRIPT }}
          EOF
          chmod +x "${{ github.run_id }}-pre.sh"
          echo "PRE_BUILD=${{ github.run_id }}-pre.sh" >> "$GITHUB_ENV"
      - name: Pre-build URL
        if: ${{ inputs.PRE_BUILD_SCRIPT_URL != '' }}
        # yamllint disable rule:line-length
        run: |
          curl -fsSL "${{ inputs.PRE_BUILD_SCRIPT_URL }}" > "${{ github.run_id }}-pre.sh"
          chmod +x "${{ github.run_id }}-pre.sh"
          echo "PRE_BUILD=${{ github.run_id }}-pre.sh" >> "$GITHUB_ENV"
        # yamllint enable rule:line-length
      - name: Run pre-build
        if: ${{ env.PRE_BUILD != '' }}
        shell: bash
        run: |
          echo "::group::Pre-build script output"
          bash -euo pipefail "$PRE_BUILD"
          echo "::endgroup::"
      - name: Run Maven
        # yamllint disable-line rule:line-length
        uses: lfreleng-actions/maven-build-action@c2ded37cb11ff1c2bb1eb7df7011906ddf97bd58 # v0.2.2
        with:
          java-version: ${{ inputs.JDK_VERSION }}
          mvn-version: ${{ inputs.MVN_VERSION }}
          mvn-params: ${{ inputs.MVN_PARAMS }}
          mvn-phases: ${{ inputs.MVN_PHASES }}
          mvn-opts: ${{ inputs.MVN_OPTS }}
          mvn-pom-file: ${{ inputs.MVN_POM_FILE }}
          mvn-profiles: ${{ inputs.MVN_PROFILES }}
          env-vars: ${{ inputs.ENV_VARS }}
          env-secrets: ${{ inputs.ENV_SECRETS }}
          global-settings: ${{ inputs.MVN_GLOBAL_SETTINGS }}
      - name: Post-build path
        if: ${{ inputs.POST_BUILD_SCRIPT_PATH != '' }}
        # yamllint disable rule:line-length
        run: |
          echo "POST_BUILD=${{ inputs.POST_BUILD_SCRIPT_PATH }}" >> "$GITHUB_ENV"
        # yamllint enable rule:line-length
      - name: Post-build script
        if: ${{ inputs.POST_BUILD_SCRIPT != '' }}
        run: |
          cat > "${{ github.run_id }}.sh" << 'EOF'
          ${{ inputs.POST_BUILD_SCRIPT }}
          EOF
          chmod +x "${{ github.run_id }}.sh"
          echo "POST_BUILD=${{ github.run_id }}.sh" >> "$GITHUB_ENV"
      - name: Post-build URL
        if: ${{ inputs.POST_BUILD_SCRIPT_URL != '' }}
        # yamllint disable rule:line-length
        run: |
          curl -fsSL "${{ inputs.POST_BUILD_SCRIPT_URL }}" > "${{ github.run_id }}.sh"
          chmod +x "${{ github.run_id }}.sh"
          echo "POST_BUILD=${{ github.run_id }}.sh" >> "$GITHUB_ENV"
        # yamllint enable rule:line-length
      - name: Run post-build
        if: ${{ env.POST_BUILD != '' }}
        shell: bash
        run: |
          echo "::group::Post-build script output"
          bash -euo pipefail "$POST_BUILD"
          echo "::endgroup::"
