---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

name: Compose Maven Merge

# yamllint disable-line rule:truthy
on:
  workflow_call:
    secrets:
      VAULT_MAPPING_JSON:
        required: true
      OP_SERVICE_ACCOUNT_TOKEN:
        required: true
    inputs:
      GERRIT_CHANGE_ID:
        description: "The ID for the change"
        required: false
        type: string
      GERRIT_BRANCH:
        description: "Branch that change is against"
        required: true
        type: string
      GERRIT_REFSPEC:
        description: "Gerrit refspec of change"
        required: false
        type: string
      JDK_VERSION:
        description: "OpenJDK version"
        required: false
        default: "17"
        type: string
      MVN_VERSION:
        description: "Maven version"
        required: false
        default: "3.8.2"
        type: string
      MAKE_TARGETS:
        description: "Make targets to pass to the make command"
        required: false
        default: "all"
        type: string

concurrency:
  # yamllint disable-line rule:line-length
  group: compose-make-merge-${{ github.workflow }}-${{ inputs.GERRIT_BRANCH }}-${{ inputs.GERRIT_CHANGE_ID || github.run_id }}
  cancel-in-progress: true

jobs:
  maven-merge:
    runs-on: ubuntu-latest
    steps:
      # Harden the runner used by this workflow
      # yamllint disable-line rule:line-length
      - uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: 'audit'

      # yamllint disable-line rule:line-length
      - uses: lfreleng-actions/checkout-gerrit-change-action@f87b90a3370e62dad310797fedc7fd3700c75832  # v1.0.2
        with:
          gerrit-refspec: ${{ inputs.GERRIT_REFSPEC }}
          gerrit-url: ${{ vars.GERRIT_URL }}
          delay: "0s"

      - name: "Load project/repository credentials"
      # yamllint disable-line rule:line-length
        uses: lfreleng-actions/credential-load-action@69d76d75b1f52779dfdfe4ec788b5dbb3face234 # v2.0.0
        with:
          vault_mapping_json: ${{ secrets.VAULT_MAPPING_JSON }}
          op_service_account_token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: Run Maven
        # yamllint disable-line rule:line-length
        uses: lfreleng-actions/maven-make-build-action@3ee8ccba910683179ea981afa0f5c8564ac6300a # v0.2.2
        with:
          jdk-version: ${{ inputs.JDK_VERSION }}
          mvn-version: ${{ inputs.MVN_VERSION }}
          make-targets: ${{ inputs.MAKE_TARGETS }}
        env:                         # map secrets into env vars
          NEXUS_PASSWORD: ${{ env.CREDENTIAL }}
