---
name: Gerrit Required INFO Yaml Verify

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      GERRIT_BRANCH:
        description: "Branch that change is against"
        required: true
        type: string
      GERRIT_CHANGE_ID:
        description: "The ID for the change"
        required: true
        type: string
      GERRIT_CHANGE_NUMBER:
        description: "The Gerrit number"
        required: true
        type: string
      GERRIT_CHANGE_URL:
        description: "URL to the change"
        required: true
        type: string
      GERRIT_EVENT_TYPE:
        description: "Type of Gerrit event"
        required: true
        type: string
      GERRIT_PATCHSET_NUMBER:
        description: "The patch number for the change"
        required: true
        type: string
      GERRIT_PATCHSET_REVISION:
        description: "The revision sha"
        required: true
        type: string
      GERRIT_PROJECT:
        description: "Project in Gerrit"
        required: true
        type: string
      GERRIT_REFSPEC:
        description: "Gerrit refspec of change"
        required: true
        type: string
      TARGET_REPO:
        # yamllint disable-line rule:line-length
        description: "The target GitHub repository needing the required workflow"
        required: true
        type: string
      comment-only:
        description: "Make this workflow advisory only, default false"
        required: false
        type: string
        default: "false"
    secrets:
      GERRIT_SSH_REQUIRED_PRIVKEY:
        description: "SSH Key for the authorized user account"
        required: true

concurrency:
  # yamllint disable-line rule:line-length
  group: reusable-${{ github.workflow }}-${{ github.event.inputs.GERRIT_CHANGE_ID || github.run_id }}
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Clear votes
        # yamllint disable-line rule:line-length
        uses: lfit/gerrit-review-action@6ac4c2322b68c0120a9b516eb0421491ee1b3fdf  # v0.4
        with:
          host: ${{ vars.GERRIT_SERVER }}
          username: ${{ vars.GERRIT_SSH_REQUIRED_USER }}
          key: ${{ secrets.GERRIT_SSH_REQUIRED_PRIVKEY }}
          known_hosts: ${{ vars.GERRIT_KNOWN_HOSTS }}
          gerrit-change-number: ${{ inputs.GERRIT_CHANGE_NUMBER }}
          gerrit-patchset-number: ${{ inputs.GERRIT_PATCHSET_NUMBER }}
          vote-type: clear
          comment-only: ${{ inputs.comment-only }}
      - name: Allow replication
        run: sleep 10s

  info-validation:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Gerrit Checkout
        # yamllint disable-line rule:line-length
        uses: lfit/checkout-gerrit-change-action@57bf0435f739fbbc7ce4cc85c9c3b8a386c6f84b  # v0.6
        with:
          gerrit-refspec: ${{ inputs.GERRIT_REFSPEC }}
          gerrit-project: ${{ inputs.GERRIT_PROJECT }}
          gerrit-url: ${{ vars.GERRIT_URL }}
          delay: "0s"
          repository: ${{ inputs.TARGET_REPO }}
          ref: refs/heads/${{ inputs.GERRIT_BRANCH }}
      # yamllint disable-line rule:line-length
      - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c  # v5.0.0
        id: setup-python
        with:
          python-version: "3.11"
      - name: Verify Change Isolation
        # yamllint disable rule:line-length
        # INFO.yaml file creation or moddifications should be kept in its own separate change.
        run: |
          set -e -o pipefail
          set +u
          MODIFIED_FILES=$(git diff --name-only HEAD~1)
          if [[ "$MODIFIED_FILES" != *"INFO.yaml"* ]]; then
            echo "No INFO.yaml found. Passing"
            echo "SCAN=false" >> "$GITHUB_ENV"
            exit 0
          elif [[ $(echo "$MODIFIED_FILES" | wc -l) -gt 1 ]]; then
            echo "ERROR: Do not combine INFO.yaml file changes with other files."
            echo "Please isolate INFO.yaml changes."
            echo "SCAN=false" >> "$GITHUB_ENV"
            exit 1
          fi
          echo "SCAN=true" >> "$GITHUB_ENV"
      - name: Download Valid Schema
        if: env.SCAN == 'true'
        # Download info-schema.yaml and yaml-verfy-schema.py
        run: |
          wget -q https://raw.githubusercontent.com/lfit/releng-global-jjb/master/schema/info-schema.yaml \
          https://raw.githubusercontent.com/lfit/releng-global-jjb/master/yaml-verify-schema.py
      - name: Info File Validation
        if: env.SCAN == 'true'
        run: |
          set -e -o pipefail
          pip install jsonschema yq
          PROJECT_INPUT=${{ inputs.GERRIT_PROJECT }}
          yamllint INFO.yaml
          python yaml-verify-schema.py \
              -s info-schema.yaml \
              -y INFO.yaml
          # Verfiy that there is only one repository and that it matches $PROJECT
          REPO_LIST="$(yq -r '.repositories[]' INFO.yaml)"
          while IFS= read -r project; do
              if [[ "$project" == "$PROJECT_INPUT" ]]; then
                  echo "$project is valid"
              else
                  echo "ERROR: $project is invalid"
                  echo "INFO.yaml file may only list one repository"
                  echo "Repository must match $PROJECT_INPUT"
                  exit 1
              fi
          done <<< "$REPO_LIST"

  vote:
    if: ${{ always() }}
    # yamllint enable rule:line-length
    needs: [prepare, info-validation]
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/workflow-conclusion-action@v3
      - name: Set vote
        # yamllint disable-line rule:line-length
        uses: lfit/gerrit-review-action@6ac4c2322b68c0120a9b516eb0421491ee1b3fdf  # v0.4
        with:
          host: ${{ vars.GERRIT_SERVER }}
          username: ${{ vars.GERRIT_SSH_REQUIRED_USER }}
          key: ${{ secrets.GERRIT_SSH_REQUIRED_PRIVKEY }}
          known_hosts: ${{ vars.GERRIT_KNOWN_HOSTS }}
          gerrit-change-number: ${{ inputs.GERRIT_CHANGE_NUMBER }}
          gerrit-patchset-number: ${{ inputs.GERRIT_PATCHSET_NUMBER }}
          vote-type: ${{ env.WORKFLOW_CONCLUSION }}
          comment-only: ${{ inputs.comment-only }}
