---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2024 The Linux Foundation

# Runs a Sonatype Lifecycle (Nexus IQ) scan on a Node.js project
name: "[R] node-sonatype-lifecycle"

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      BUILD_TOOL:
        description: "Used to build Node.js project [npm|yarn]"
        required: false
        type: string
        default: "npm"
      NODE_VERSION:
        description: "Node.js version to use for build"
        required: false
        type: number
        default: 20
      JAVA_DISTRIBUTION:
        description: "JAVA SE distribution to setup/run for Nexus CLI tool"
        required: false
        type: string
        default: "temurin"
      JAVA_VERSION:
        description: "Java runtime to setup/run for Nexus CLI tool"
        required: false
        type: number
        default: 17
      IQ_CLI_VERSION:
        description: "Specific version of Nexus CLI to setup/run"
        required: false
        type: string
        default: "1.179.0-01"
      APPLICATION_ID:
        description: "Organisation and project name in Nexus IQ"
        required: false
        type: string
        # yamllint disable-line rule:line-length
        default: ${{ github.repository_owner }}-${{ github.event.repository.name }}
      SCAN_TARGETS:
        description: "Location of file(s) or folder(s) to scan"
        required: false
        type: string
        default: "."
    # Re-usable workflow requires secrets be explicitly passed
    secrets:
      NEXUS_IQ_PASSWORD:
        description: "Nexus IQ Password"
        required: true

jobs:
  node-sonatype-cli:
    name: "Node.js Sonatype Lifecycle"
    runs-on: ubuntu-latest
    steps:
      # Checkout code when GitHub is NOT a Gerrit mirror
      - name: "Checkout GitHub repository"
        if: ${{ vars.GERRIT_MIRROR != 'true' }}
        uses: actions/checkout@v4

      - name: "Build Node.js project"
        # yamllint disable-line rule:line-length
        uses: lfit/releng-reusable-workflows/.github/actions/node-build-action@5db64208d04fdb0558e8a3a1a1a762b88ffd483e # Initial release
        with:
          node-version: ${{ inputs.NODE_VERSION }}
          build-tool: ${{ inputs.BUILD_TOOL }}

      - name: Setup Sonatype CLI
        uses: sonatype/actions/setup-iq-cli@v1
        with:
          iq-cli-version: ${{ inputs.IQ_CLI_VERSION }}

      # Sonatype CLI requires Java to run
      - name: Setup Java runtime
        uses: actions/setup-java@v4
        with:
          distribution: ${{ inputs.JAVA_DISTRIBUTION }}
          java-version: ${{ inputs.JAVA_VERSION }}

      - name: Run Sonatype CLI
        uses: sonatype/actions/run-iq-cli@v1
        with:
          iq-server-url: ${{ vars.NEXUS_IQ_SERVER }}
          username: ${{ vars.NEXUS_IQ_USERNAME }}
          password: ${{ secrets.NEXUS_IQ_PASSWORD }}
          application-id: ${{ inputs.APPLICATION_ID }}
          scan-targets: ${{ inputs.SCAN_TARGETS }}
